name: Build/release

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --network-timeout 600000

      - name: build
        run: yarn build

        env:
          TBA_API_KEY: ${{ secrets.TBA_API_KEY }}
