name: Build And Release
on: [push]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.github_token }}

jobs:
  build-executables:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run make
        env:
          MODE: 'production'
          TBA_KEY: ${{ secrets.NEXT_PUBLIC_TBA_KEY }}
          FLUENTFFMPEG_COV: 'false'
      - name: publish
        run: npm run publish
        env:
          MODE: 'production'
          TBA_KEY: ${{ secrets.NEXT_PUBLIC_TBA_KEY }}
          FLUENTFFMPEG_COV: 'false'
